=== cyye76/PolarisEngine/scripts/Schema/ServiceSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ServiceSchema" xmlns:tns="http://www.example.org/ServiceSchema" elementFormDefault="qualified">

    <element name="Service" type="tns:ServiceDefinition"></element>
    
    <complexType name="ServiceDefinition">
    	<sequence>
            <element name="Name" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="Variables" type="tns:VariablesListType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Activities" type="tns:ActivityList"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Transitions" type="tns:TransitionList"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="StartTask" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="VariablesListType">
    	<sequence>
    		<element name="Variable" type="tns:VariableType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ActivityList">
    	<sequence>
    		<element name="Activity" type="tns:ActivityDefinition" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TransitionList">
    	<sequence>
    		<element name="Transition" type="tns:TransitionType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="VariableType">
    	<sequence>
    		<element name="Name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Type" type="tns:DataType" maxOccurs="1" minOccurs="1"></element>
    		<element name="Value" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <simpleType name="DataType">
    	<restriction base="string">
    		<enumeration value="STRING"></enumeration>
    		<enumeration value="INTEGER"></enumeration>
    		<enumeration value="BOOLEAN"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="ActivityDefinition">
    	<sequence>
    		<element name="Name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Type" type="tns:ActivityType" maxOccurs="1" minOccurs="1"></element>
    		<element name="Effect" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <simpleType name="ActivityType">
    	<restriction base="string">
    		<enumeration value="LocalTask"></enumeration>
    		<enumeration value="ReceiveTask"></enumeration>
    		<enumeration value="SendTask"></enumeration>
    		<enumeration value="Service"></enumeration>
    	</restriction>
    </simpleType>
    
    <complexType name="TransitionType">
    	<sequence>
    		<element name="Name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Source" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Sink" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Guard" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== cyye76/PolarisEngine/Applications/LoanApproval/Approval.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Service xmlns:tns="http://www.example.org/ServiceSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ServiceSchema ../../src/scripts/Schema/ServiceSchema.xsd ">
  <tns:Name>Approval</tns:Name>
  <tns:Variables>
    <tns:Variable>
      <tns:Name>amount</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>rejected</tns:Name>
      <tns:Type>BOOLEAN</tns:Type>
      <tns:Value>true</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>actual_approval</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>    
    <tns:Variable>
      <tns:Name>ApprovalRequest</tns:Name>
      <tns:Type>STRING</tns:Type>
      <tns:Value>random</tns:Value>
    </tns:Variable> 
    <tns:Variable>
      <tns:Name>ICMutationVariable</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>0</tns:Value>
    </tns:Variable>     
    <tns:Variable>
      <tns:Name>RandomVariable</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>1~99</tns:Value>
    </tns:Variable>
  </tns:Variables>
  <tns:Activities>
    <tns:Activity>
      <tns:Name>task1</tns:Name>
      <tns:Type>ReceiveTask</tns:Type>
      <tns:Effect>receive amount ApprovalRequest</tns:Effect>
    </tns:Activity>
    <tns:Activity>
      <tns:Name>task2</tns:Name>
      <tns:Type>ReceiveTask</tns:Type>
      <tns:Effect>receive rejected</tns:Effect>
    </tns:Activity>
    <tns:Activity>
      <tns:Name>task3</tns:Name>
      <tns:Type>LocalTask</tns:Type>
      <tns:Effect><![CDATA[actual_approval:=0;]]></tns:Effect>
    </tns:Activity>
    <tns:Activity>
      <tns:Name>task4</tns:Name>
      <tns:Type>SendTask</tns:Type>
      <tns:Effect>send actual_approval</tns:Effect>
    </tns:Activity>    
    <tns:Activity>
      <tns:Name>task5</tns:Name>
      <tns:Type>LocalTask</tns:Type>
      <tns:Effect><![CDATA[actual_approval:=amount;]]></tns:Effect>
    </tns:Activity>    
  </tns:Activities>
  <tns:Transitions>
    <tns:Transition>
      <tns:Name>t1</tns:Name>
      <tns:Source>task1</tns:Source>
      <tns:Sink>task2</tns:Sink>
      <tns:Guard><![CDATA[amount<90]]></tns:Guard>
    </tns:Transition>
    <tns:Transition>
      <tns:Name>t2</tns:Name>
      <tns:Source>task2</tns:Source>
      <tns:Sink>task3</tns:Sink>
      <tns:Guard><![CDATA[rejected == true]]></tns:Guard>
    </tns:Transition>
    <tns:Transition>
      <tns:Name>t3</tns:Name>
      <tns:Source>task3</tns:Source>
      <tns:Sink>task4</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    <tns:Transition>
      <tns:Name>t4</tns:Name>
      <tns:Source>task2</tns:Source>
      <tns:Sink>task5</tns:Sink>
      <tns:Guard><![CDATA[rejected == false]]></tns:Guard>
    </tns:Transition>
    <tns:Transition>
      <tns:Name>t5</tns:Name>
      <tns:Source>task1</tns:Source>
      <tns:Sink>task3</tns:Sink>
      <tns:Guard><![CDATA[amount >= 90]]></tns:Guard>
    </tns:Transition>
    <tns:Transition>
      <tns:Name>t6</tns:Name>
      <tns:Source>task5</tns:Source>
      <tns:Sink>task4</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
  </tns:Transitions>
  <tns:StartTask>task1</tns:StartTask>
</tns:Service>

=== cyye76/PolarisEngine/Applications/Insurance/Assessor.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Service xmlns:tns="http://www.example.org/ServiceSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ServiceSchema ../../src/scripts/Schema/ServiceSchema.xsd ">
  <tns:Name>Assessor</tns:Name>
  <tns:Variables>
    <tns:Variable>
      <tns:Name>claimprice</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>needNegotiate</tns:Name>
      <tns:Type>BOOLEAN</tns:Type>
      <tns:Value>false</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>finalCost</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>repairCharge</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>ICMutationVariable</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>0</tns:Value>
    </tns:Variable>      
    <tns:Variable>
      <tns:Name>RandomVariable</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>1~99</tns:Value>
    </tns:Variable>
  </tns:Variables>
  <tns:Activities>
    <tns:Activity>
      <tns:Name>obtaintask</tns:Name>
      <tns:Type>ReceiveTask</tns:Type>
      <tns:Effect>receive claimprice</tns:Effect>
    </tns:Activity>    
    
    <tns:Activity>
      <tns:Name>inspectcar</tns:Name>
      <tns:Type>LocalTask</tns:Type>
      <tns:Effect><![CDATA[needNegotiate := claimprice > 500 ;]]></tns:Effect>
    </tns:Activity>    
    
    <tns:Activity>
      <tns:Name>sendnegotiaterequest</tns:Name>
      <tns:Type>SendTask</tns:Type>
      <tns:Effect>send needNegotiate</tns:Effect>
    </tns:Activity>
    
    <tns:Activity>
      <tns:Name>receivecharge</tns:Name>
      <tns:Type>ReceiveTask</tns:Type>
      <tns:Effect>receive repairCharge</tns:Effect>
    </tns:Activity>
    
    <tns:Activity>
      <tns:Name>preparereport1</tns:Name>
      <tns:Type>LocalTask</tns:Type>
      <tns:Effect><![CDATA[finalCost := repairCharge;]]></tns:Effect>
    </tns:Activity>
    
    <tns:Activity>
      <tns:Name>preparereport2</tns:Name>
      <tns:Type>LocalTask</tns:Type>
      <tns:Effect><![CDATA[finalCost := claimprice;]]></tns:Effect>
    </tns:Activity>
    
    <tns:Activity>
      <tns:Name>reportfinalcost</tns:Name>
      <tns:Type>SendTask</tns:Type>
      <tns:Effect>send finalCost</tns:Effect>
    </tns:Activity>
    
  </tns:Activities>
  <tns:Transitions>
    <tns:Transition>
      <tns:Name>t1</tns:Name>
      <tns:Source>obtaintask</tns:Source>
      <tns:Sink>inspectcar</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t2</tns:Name>
      <tns:Source>inspectcar</tns:Source>
      <tns:Sink>sendnegotiaterequest</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t3</tns:Name>
      <tns:Source>sendnegotiaterequest</tns:Source>
      <tns:Sink>preparereport2</tns:Sink>
      <tns:Guard><![CDATA[!needNegotiate]]></tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t4</tns:Name>
      <tns:Source>sendnegotiaterequest</tns:Source>
      <tns:Sink>receivecharge</tns:Sink>
      <tns:Guard><![CDATA[needNegotiate]]></tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t5</tns:Name>
      <tns:Source>receivecharge</tns:Source>
      <tns:Sink>preparereport1</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t6</tns:Name>
      <tns:Source>preparereport1</tns:Source>
      <tns:Sink>reportfinalcost</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    
    <tns:Transition>
      <tns:Name>t7</tns:Name>
      <tns:Source>preparereport2</tns:Source>
      <tns:Sink>reportfinalcost</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
    
  </tns:Transitions>
  <tns:StartTask>obtaintask</tns:StartTask>
</tns:Service>

=== cyye76/PolarisEngine/Applications/BookOrdering/BookOrderingClient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Service xmlns:tns="http://www.example.org/ServiceSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ServiceSchema ../../src/scripts/Schema/ServiceSchema.xsd ">
  <tns:Name>BookOrderingClient</tns:Name>
  <tns:Variables>
    <tns:Variable>
      <tns:Name>amount</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>account_credit</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>confirm</tns:Name>
      <tns:Type>BOOLEAN</tns:Type>
      <tns:Value>true</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>hasInterests</tns:Name>
      <tns:Type>BOOLEAN</tns:Type>
      <tns:Value>true</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>customerID</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>new_amount</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>creditcard_credit</tns:Name>
      <tns:Type>INTEGER</tns:Type>
      <tns:Value>-1</tns:Value>
    </tns:Variable>
    <tns:Variable>
      <tns:Name>notification</tns:Name>
      <tns:Type>BOOLEAN</tns:Type>
      <tns:Value>true</tns:Value>
    </tns:Variable>
  </tns:Variables>
  <tns:Activities>
    <tns:Activity>
      <tns:Name>task1</tns:Name>
      <tns:Type>SendTask</tns:Type>
      <tns:Effect>send amount account_credit confirm hasInterests customerID new_amount creditcard_credit </tns:Effect>
    </tns:Activity>
    <tns:Activity>
      <tns:Name>task2</tns:Name>
      <tns:Type>ReceiveTask</tns:Type>
      <tns:Effect>receive notification</tns:Effect>
    </tns:Activity>
  </tns:Activities>
  <tns:Transitions>
    <tns:Transition>
      <tns:Name>t1</tns:Name>
      <tns:Source>task1</tns:Source>
      <tns:Sink>task2</tns:Sink>
      <tns:Guard>true</tns:Guard>
    </tns:Transition>
  </tns:Transitions>
  <tns:StartTask>task1</tns:StartTask>
</tns:Service>
